// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: (() => {
      const url = process.env["DATABASE_URL"];
      // Workaround: Prisma Studio does not support "prisma+postgres://" protocol with localhost yet.
      // We extract the underlying postgres URL from the api_key if running studio.
      const isStudio = process.argv.some((arg) => arg.includes("studio"));

      if (isStudio && url && url.startsWith("prisma+postgres://")) {
        try {
          const parsed = new URL(url);
          const apiKey = parsed.searchParams.get("api_key");
          if (apiKey) {
            const decoded = Buffer.from(apiKey, "base64").toString("utf-8");
            const json = JSON.parse(decoded);
            if (json.databaseUrl) {
              return json.databaseUrl;
            }
          }
        } catch (e) {
          console.warn("Failed to extract databaseUrl from prisma+postgres URL for Studio:", e);
        }
      }
      return url;
    })(),
  },
});
